### ISSUE TITLE
[BUG] Only the first calendar in config is loading

### ISSUE THREAD

**Issue by artaxx81** [PTST/O365-HomeAssistant#40]
**Describe the bug**
Since 0.105.0 only the first calendar in the list is loading

**To Reproduce**
1. Configure as always
2. See only the first calendar loading

**Expected behavior**
All calendars should be loaded

**Installation method (please select one):**
- [X] HACS
- [X] Manual Installation

**Additional context**
These are the attributes since 0.105.0
```
data: [object Object],[object Object]
calendar_id: AAMkADZlYjQ4YzVjLTAyYjQtNDRlYi05MTMwLWQzNDMwY2NmMDQ3MgBGAAAAAACMxiT4r3KUTLubbwPEBuciBwDE2oNYc5kjT7TXqMpClzJTAAAAVwjKAAAegiUP3rX5RqIMKiubJHzGACIYFgICAAA=
event_active: false
friendly_name: Events
```

- [ ] Home assistant logs attached
[ha.txt](https://github.com/PTST/O365-HomeAssistant/files/4162485/ha.txt)

**Comment by PTST** [comment]
What do you mean by only one calendar is loading? 
Each entity is one calendar so are you missing a calendar entity for a configured entity, if so please post your configuration.yaml

If you believe you are missing event on this one calendar, please be aware that I removed the data_str_repr attribute, since it unnecessarily cluttered up the entities list.  
If you try ant select the calendar entity in your states list the data attribute will actually be shown rather than just displaying [object Object],[object Object]

**Comment by artaxx81** [comment]
This is my configuration:

```
o365:
  client_secret: "xxx"
  client_id: "xxx"
  calendars:
    - calendar_name: "Events"
      name: Events
      start_offset: 0
      end_offset: 168
    - calender_name: "Urlaub"
      name: Urlaub
      start_offset: 0
      end_offset: 168
    - calendar_name: "Entsorgungskalender"
      name: Entsorgungskalender
      start_offset: 0
      end_offset: 168
    - calendar_name: "Privat"
      name: Privat
      start_offset: 0
      end_offset: 168
    - calendar_name: "Geschäftlich"
      name: Geschäftlich
      start_offset: 0
      end_offset: 168
    - calendar_name: "Geburtstage"
      name: Geburtstage
      start_offset: 0
      end_offset: 168
```

I only get an entity for the first calendar (Events). And as I've seen this calendar doesn't show calendar events at all. The rest from the calendar list in the configuration won't appear in HA.

**Comment by PTST** [comment]
You have a spelling mistake in you "Urlaub" entry
its calend**a**r_name (a not e in calendar)

**Comment by artaxx81** [comment]
Ah, I see ... that was the problem why this calendar wasn't shown prior to 0.105.0

But unfortunately that doesn't solve the other problem :-(

**Comment by PTST** [comment]
Are you sure there is a problem, as explained earlier the entity no longer displays the events as a giant string, but as actual data object that the automations can interact with. That is the "[object Object],[object Object]..." part you see under the data attribute.

If you want to manually see what elements are in the data attribute, simply select the entity in Developer Tools/States and you should see all of your events like so:
![calendar_entity](https://user-images.githubusercontent.com/17211264/73915975-c4248280-48bc-11ea-9e94-df75defb419f.png)

**Comment by artaxx81** [comment]
Ah, okay. Yes, the giant string wasn't that cool but I was able to handle it with regex.

Here my state attributes:

```
data:
  - subject: Unicorne Inn
    body: ''
    location: |-
      Äußere Münchener Straße 65
      84036 Landshut
    categories: []
    sensitivity: Normal
    show_as: Busy
    is_all_day: false
    attendees: []
    start: '2020-02-06T18:00:00+0100'
    end: '2020-02-06T20:00:00+0100'
    event_active: false
    event_id: >-
      AAMkADZlYjQ4YzVjLTAyYjQtNDRlYi05MTMwLWQzNDMwY2NmMDQ3MgFRAAgI16qXglsAAEYAAAAAjMYk_K9ylEy7m28DxAbnIgcAxNqDWHOZI0_016jKQpcyUwAAL54g2AAAzdGGyoMzdkOCNUST-XCaSQAGFa6BZAAAEA==
    calendar_id: >-
      AAMkADZlYjQ4YzVjLTAyYjQtNDRlYi05MTMwLWQzNDMwY2NmMDQ3MgBGAAAAAACMxiT4r3KUTLubbwPEBuciBwDE2oNYc5kjT7TXqMpClzJTAAAAVwjKAAAegiUP3rX5RqIMKiubJHzGACIYFgICAAA=
  - subject: sunshine live Classics
    body: ''
    location: ''
    categories: []
    sensitivity: Normal
    show_as: Busy
    is_all_day: false
    attendees:
      - email: xxx
        type: required
    start: '2020-02-08T09:00:00+0100'
    end: '2020-02-08T13:00:00+0100'
    event_active: false
    event_id: >-
      AAMkADZlYjQ4YzVjLTAyYjQtNDRlYi05MTMwLWQzNDMwY2NmMDQ3MgFRAAgI16wp1y6AAEYAAAAAjMYk_K9ylEy7m28DxAbnIgcAxNqDWHOZI0_016jKQpcyUwAAL54g2AAAzdGGyoMzdkOCNUST-XCaSQADid7VWQAAEA==
    calendar_id: >-
      AAMkADZlYjQ4YzVjLTAyYjQtNDRlYi05MTMwLWQzNDMwY2NmMDQ3MgBGAAAAAACMxiT4r3KUTLubbwPEBuciBwDE2oNYc5kjT7TXqMpClzJTAAAAVwjKAAAegiUP3rX5RqIMKiubJHzGACIYFgICAAA=
calendar_id: >-
  AAMkADZlYjQ4YzVjLTAyYjQtNDRlYi05MTMwLWQzNDMwY2NmMDQ3MgBGAAAAAACMxiT4r3KUTLubbwPEBuciBwDE2oNYc5kjT7TXqMpClzJTAAAAVwjKAAAegiUP3rX5RqIMKiubJHzGACIYFgICAAA=
event_active: false
friendly_name: Events
```

As you can see: There are only data from the "Events" calendar and the state is false although my weekly Guinness drinking day is today at 6 pm (that might be right if it only turns to true when either the event is running or there is an all day event?)
