### ISSUE TITLE
Calendars not retrieving data

### ISSUE THREAD

**Issue by gijbelsy** [PTST/O365-HomeAssistant#69]
# Problem:
The integration stopped working for me.
I  can't pinpoint exactly when, but here is the scenario:

- Client ID & secret are correct;

- Application is authorized;

- o365_calendars.yaml is being (re-)created;

- Requested calendars are being registered in HA;

- No data is retrieved from office 365 calendar (data attribute remains empty), even there is data present.

This last step is where it goes wrong.
I have 3 calendars listed, all filled with data the next 24hrs, but none is showing any events.
```yaml
offset_reached: false
data: 
friendly_name: myCalendar
```

```yaml
- cal_id: !secret
  entities:
  - device_id: myCalendar
    end_offset: 24
    name: My Calendar
    start_offset: 0
    track: true
```
# Versions
Home Assistant Version: 0.109.6
o365 version: v2.1.7
System | HassOS 3.13
